# For beginners

## More words of encouragement

Getting research experience in your first years of undergrad is quite rare - but not impossible! Here are some of the things that you can do to get into research without having ANY experience.

## Edinburgh Scientific Researchers Association (ESRA)

**About **

- ESRA is a society just like any other but with a special aim to promote independent undergraduate research projects - this is cool.

- Essentially, here you can come up with a small research project on your own (or in pairs or groups) and lead it from conception to final write up and presentation.

- ESRA has different 'departments' - one of which is the Social Sciences department, which serves as a platform ( a place to meet) for you to brainstorm and develop your experiment with other students interested in social sciences (this is usually Psychology, Linguistics or Philosophy students)

- The head of the Social Sciences department will help you finalise your idea. Then you can write your proposal (which will get approved by ESRA), submit an ethics form, and then you can go on and collect your data (or do secondary data analysis / or even a lit review) and finally make a poster at the end, which you can present at the ESRA conference at the end of the academic year.

- All these skills above are exactly the skills you need to develop to be a great researcher - and this is a good place to start. There is no pressure, even no need to actually finish the project. You are the boss of your research.

- Also also, ESRA will even give you funding to conduct your research, which is great!

- The skills you develop in ESRA, and the fact that you even participate in a small conference, you can put on your CV or talk about when you are applying for actual research placements or Volunteer Research Assistant (VRA) positions. PsyCRA members corroborate (this is what got us some of the cool opportunities that are further along this document)


**What you need to do**

- Join ESRA at the start of the semester 

- Go to the Social Sciences department meetings - they usually happen every week

**Where to find more info**

- [ESRA EUSA page](https://www.eusa.ed.ac.uk/activities/view/ESRA)

- [ESRA Instagram](https://www.instagram.com/esra.soc/)


## Volunteer Research Assistant (VRA) programme (Rare in pre-honours)

**About**

- You might get an email from the psychology department about this.

- The purpose of this programme is to offer undergraduate Psychology students the opportunity to acquire additional research experience in the field, working with an established researcher (somebody in the department).

- This is a great opportunity to get to know the research that is going on in the department, and also to get to know the researchers here.

- It's hard to predict what exactly you will be doing, as it varies depending on what research projects are being conducted.

- But in general, I would recommend just going with whatever you are assigned to and making the most of it, because you will never know what area might interest you!

- Priority is given to 3rd and 4th years for this, so it's best not to have your expectations too high, but there are first or second years that did do this!

**What you need to do**

- Fill out a survey that the department will send out.

- There, you will have to tell them some of your grades (it's advantageous if your grades are good), write a short statement as to why you want to be a volunteer research assistant, and indicate which areas interest you (there is no guarantee you will get something you are specifically interested in, but that's okay, just go with what you get).

- You will help with whatever needs to be done for the research project, usually lasting a semester (but you can also agree with your supervisor to continue for longer if it interests you and there is more work to do)

**Where to find more info**

- The department sends an email :)


## Student-led, Individually-created Courses (SLICC)

- I don't known a tonne about this, but I do know they have a website which you can check out and find out more! Here: [SLICC](https://sliccs.ed.ac.uk)


## Emailing

- It's okay to email a lecturer and ask if you can help with their research in any way, or ask for advice

- This is very much a “right place, right time” thing, they might not have any work suitable for you but it never hurts to ask and they will remember your interest!

- Do not ask post-docs or PhDs directly, you need to go through the lecturer/researcher heading the research they are working on

- You can also talk to your cohort lead and the [career service](https://careers.ed.ac.uk) - set up a meeting!


## Skills development

- You can also work on your skills independently - best skills to develop would be R programming, working with Excel, Qualtrics, or learning a new programming language (like Python or Matlab)

- In general, it doesn't hurt to have good marks at uni :) sometimes when you are applying for positions, they look at your transcript, so it's good to have a strong one!









